### ISSUE TITLE
[Feature suggestion] data-valuetype

### ISSUE THREAD

**Issue by Lailend** [lightswitch05/table-to-json#14]
Maybe it is a good idea to add something like a data-valuetype attribute to the plugin so that you can parse the field for a specific type.
Currently everything gets returned as a string and it would be awesome if we could set in the table what kind of a type a certain value is and that the json returned from the table tries to parse the value's by the supplied data-valuetype.

**Comment by Mottie** [comment]
Hey @lightswitch05!

I added a `textExtractor` branch which should fix this issue and #16. I didn't merge it into the main just in case you wanted to tweak it some more.

The readme contains examples on how to use the new `textExtractor` option.

**Comment by lightswitch05** [comment]
@Mottie thanks for getting this added! I'm fine with getting it merged and tagged for a new release. I'll need to port the functionality to the `rewrite` branch. It is very close be being completed, I just haven't figured out how to do `colspan` with the new design.

**Comment by Mottie** [comment]
I did look at the rewrite code, I think the reason it doesn't work is because it needs to process all the columns & rows first... so `colspan` and `rowspan` data can be set up, then process the ignore rows/columns.

I was going to work on it, but it's a bit convoluted, and the `tabletojson-row.js` and `tabletojson-cell.js` scripts need to be more tightly knit together.
